In [2]:
from selenium import webdriver
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup

In [3]:
import numpy as np
import pandas as pd

In [4]:
chrome_options = Options()
chrome_options.add_argument("--headless")


# webdriver 설정(Chrome, Firefox 등) - 일반 모드
browser = webdriver.Chrome('webdriver/chromedriver.exe')

In [5]:
# 크롬 브라우저 내부 대기
browser.implicitly_wait(5)

# 브라우저 사이즈
#browser.set_window_size(1920, 1280)  # maximize_window(), minimize_window()

# 페이지 이동
browser.get('https://www.ministop.co.kr/MiniStopHomePage/page/event/plus1.do')


WebDriverWait(browser, 2).until(EC.presence_of_element_located((By.CSS_SELECTOR, 'div.inner.wrap.service1 > ul > li:nth-child(2) > a'))).click() 
soup = BeautifulSoup(browser.page_source, "html.parser")

In [6]:
n=0
for i in range(0,8):
    WebDriverWait(browser, 2).until(EC.presence_of_element_located((By.CSS_SELECTOR, 'div.inner.wrap.service1 > div.event_plus_list > div > a.pr_more'))).click() 
    time.sleep(5)
    n+=1
    
soup = BeautifulSoup(browser.page_source, "html.parser")
pro_list = soup.select('div.inner.wrap.service1 > div.event_plus_list > ul>li ')

In [34]:
prod_list=[]
price_list=[]

for v in pro_list:
    prodname=v.select('a>img')[0]["alt"]
    prod_list.append(prodname)
    price=v.select('p>strong')[0].text.strip()
    price=price.replace(",","")
    price_list.append(price)

In [35]:
prod_list

['잼있는쿠키',
 '매일)99원액두유190ml',
 '매일)헬로엔요200ml',
 '스키피피넛버터우유190ml',
 '롯데진복분자180ml',
 '델몬트180ml',
 '신)제주삼다수500',
 '아로골드D드링크',
 '홍삼한뿌리120병',
 '한뿌리마120병',
 '인삼한뿌리',
 '멕소롱골드액75ml',
 '모닝케어강황100ml',
 '백두산백산수330펫',
 '백두산백산수2L',
 '백두산백산수500',
 '이토엔)오이오녹차525펫',
 '모닝케어',
 '보성말차500펫',
 '헛개컨디션',
 '숙취파트너100ml병',
 '네버다이247(숙취해소음료)',
 '약수동해장음료100ml',
 '생생톤180ml병',
 '벡셀에너지드링크250캔',
 '프)더블샷라떼커피캔',
 '포카리스웨트340펫',
 '패너아이스티복숭아500펫',
 '오로나민C',
 '블랙보리라이트520펫',
 '데자와밀크티250캔',
 '제주사랑감귤사랑500펫',
 '자연은제주감귤500펫',
 '자연은포도중펫',
 '자연은알로에중펫',
 '웅진초록매실500펫',
 '웅진아침햇살340펫',
 '태양의식후비법W차500펫',
 '코카)갈아만든배340캔',
 '코카)코코팜포도340캔',
 '강원평창수2L펫',
 '신)강원평창수500펫',
 '아이시스8.0',
 '제주사이다멜론350펫',
 '헬씨올리고칼슘드링크100ml병',
 '미에로화이바350펫',
 '레드불에너지드링크355캔',
 '진로석수2L',
 '진로석수500ml',
 '초정탄산수라임350펫',
 '아워홈)지리산수2L',
 '아워홈)지리산수500펫',
 '후디스)카카오닙스차500펫',
 '하이트제로캔',
 '뉴토닉워터펫',
 '일화맥콜250캔',
 '일화맥콜500펫',
 '17차500펫',
 '비타500캔',
 '광동헛개파워',
 '토레타240캔',
 '코카)토레타500펫',
 '암바사345캔',
 '아침헛개500',
 '프레주한라봉제주감귤240캔',
 '알로에베라킹500ml',
 '맛있는숙취해소레디큐',
 '광동)야왕비수리차500ml',
 '광동비타500병180ml',
 '게토레이레몬캔',
 '사각사각꿀배340캔',
 '컨디션헛개수340펫',
 '컨디션헛개수1L',
 '스프라이트355캔',
 '조지아크래프트470펫',
 '새싹보리500펫',
 '핫식스355캔',
 '요랄라340캔',
 '미스터초이스300캔',
 '신)게토레이레몬중펫',
 '트로피카나스파클링355캔',
 '롯데)목단비국화차500펫',
 '자색옥수수수염차500펫',
 '신)칸타타',
 '2%500펫',
 '영진구론산오리지날150ml',
 '트레비탄산수펫',
 '광동)500펫',
 '코코320펫',
 '복숭아아이스티340펫',
 '천호)70ml',
 '델몬트400펫',
 '글라소',
 '티오피380캔',
 '티오피중캔',
 '콜롬비아나마스터500펫',
 '고티카390캔',
 '고티카콜드브루265캔',
 '밀키스500펫',
 '칠성스트롱사이다400펫',
 '칸타타콘트라베이스500펫',
 '칸타타275캔',
 '맛있는오뚜기작은밥150g',
 '씨즈꿀차',
 '종가집김치160g',
 '킹커피아메리카노15T',
 '알레안드로아프리카',
 '수프리모아이스20T',
 '네스티20T',
 '수프리모크레마원컵',
 '카페베네15T',
 '프)카페믹스20T',
 '담터)15곡미숫가루12T',
 '허쉬초코크런치50g',
 '콜드브루',
 '명태채볶음50g',
 '돼지고기장조림110g',
 '조이웰망고345g',
 '로스팜엔네이처마일드',
 '사조 살코기참치',
 '동원참치',
 '오뚜기황도400g',
 '불닭맛김3입',
 '양반죽',
 '비비고전복죽',
 '비비고소고기죽',
 '콘스프',
 '동원들기름김3P',
 '오뚜기사골곰탕500g',
 '오뚜기육개장500g',
 '3분카레매운맛',
 '오뚜기맛있는밥210g',
 '오뚜기죽',
 '오뚜기컵밥',
 '고메로제치킨180g',
 '햇반컵반콩나물국밥',
 '햇반컵반낙지콩나물비빔밥',
 'CJ둥근햇반3입',
 '둥근햇반210',
 '햇반흑미밥210g',
 '일품팥빙수',
 '스키피바',
 '아맛나빙수',
 '설레임밀크쉐이크',
 '리얼빅구슬아이스파인애플앤포도',
 '다츠앤크림',
 '탱크보이',
 '빙그레메로나바나나',
 '한입피자',
 '이오트웬티즈150',
 '아침에주스오렌지',
 '빙)빅요구르트280ml',
 '매일)빅요구르트로어슈거280ml',
 '커피빈콜드브루280ml',
 '베지밀병에이',
 '베지밀국산검은콩두유',
 '베지밀검은콩고칼슘팩',
 '밀스드링킹딸기300ml',
 '스파클링야쿠르트280ml',
 '빙)바나나라이트',
 '사과사과해330ml',
 '천호)웰스110ml',
 '야쿠르트280ml',
 '야쿠르트270ml',
 '매일)아몬드브리즈190ml',
 '빙)사과랑야채190ml',
 '매일)아몬드브리즈190ml',
 '푸르밀)230ml',
 '제주말차우유245ml',
 '요쿠르트260ml',
 '콜드브루270ml',
 '커피빈바닐라라떼250ml',
 '빙)쥬시쿨에이드250ml',
 '빙)잇츠라떼320ml',
 '과일야채샐러드100',
 '카페베네)카페라떼',
 '서울우유300ml',
 '액티비아업210ml',
 '동서)티오피스무스240',
 '티오피300ml']

In [36]:
price_list

['900',
 '1000',
 '800',
 '1200',
 '1200',
 '1200',
 '950',
 '1000',
 '5000',
 '2500',
 '4000',
 '1000',
 '5000',
 '800',
 '1700',
 '950',
 '2000',
 '4500',
 '2200',
 '5000',
 '5000',
 '5000',
 '3900',
 '1000',
 '1200',
 '1400',
 '1500',
 '1800',
 '1000',
 '1500',
 '1300',
 '1600',
 '1500',
 '1700',
 '1900',
 '1900',
 '1500',
 '1800',
 '1100',
 '1000',
 '1400',
 '950',
 '850',
 '1500',
 '1000',
 '1800',
 '2900',
 '1550',
 '900',
 '1200',
 '1400',
 '800',
 '1700',
 '1450',
 '1200',
 '1200',
 '1700',
 '1500',
 '1200',
 '4500',
 '1200',
 '1800',
 '1300',
 '1800',
 '1000',
 '1900',
 '5000',
 '2000',
 '1300',
 '1000',
 '1000',
 '1500',
 '2500',
 '1500',
 '2500',
 '2000',
 '2000',
 '1400',
 '1200',
 '2000',
 '1200',
 '1500',
 '1500',
 '1300',
 '1700',
 '1000',
 '1600',
 '1600',
 '1500',
 '1000',
 '1900',
 '1900',
 '2000',
 '2900',
 '2200',
 '2500',
 '2900',
 '2500',
 '1700',
 '1700',
 '2500',
 '2200',
 '1300',
 '1300',
 '2900',
 '4000',
 '1500',
 '6000',
 '5500',
 '1200',
 '5400',
 '5000',
 '3900',
 '1500',
 '2000',
 '3000',
 '3300',
 '5400',
 '4500',
 '3300',
 '3600',
 '3000',
 '1300',
 '3500',
 '4200',
 '3900',
 '3000',
 '600',
 '1900',
 '2900',
 '1700',
 '1550',
 '3200',
 '3500',
 '5500',
 '3500',
 '4500',
 '4900',
 '1800',
 '2400',
 '3000',
 '2000',
 '2500',
 '1800',
 '1500',
 '1500',
 '1200',
 '1000',
 '1900',
 '1000',
 '1200',
 '1200',
 '1200',
 '2500',
 '1300',
 '1500',
 '1000',
 '3000',
 '1300',
 '1400',
 '2000',
 '1200',
 '1300',
 '2300',
 '1000',
 '1500',
 '1200',
 '2000',
 '2000',
 '1300',
 '2500',
 '2500',
 '1500',
 '2500',
 '1500',
 '1600',
 '1500',
 '1800',
 '1800',
 '2200']

In [38]:
df_ministop_twoplusone=pd.DataFrame({"품명":prod_list, "가격":price_list,"행사명":"2+1"})

In [39]:
df_ministop_twoplusone.head()

               품명    가격  행사명
0           잼있는쿠키   900  2+1
1  매일)99원액두유190ml  1000  2+1
2    매일)헬로엔요200ml   800  2+1
3  스키피피넛버터우유190ml  1200  2+1
4     롯데진복분자180ml  1200  2+1

In [33]:
#df_raw.to_csv("../project_file/df_twoplusone.csv", encoding="utf-8")

In [40]:
# conda install pymysql -c conda-forge

from sqlalchemy import create_engine
import pymysql

# mysql 연결정보 => host 127.0.0.1 / 사용자 root  / 암호 1234  / 데이터베이스명 flask_db
engine = create_engine('mysql+pymysql://root:1243@127.0.0.1/conv_db?charset=utf8', convert_unicode=True, echo=True)
conn = engine.connect()

df_ministop_twoplusone.to_sql(name='df_ministop_twoplusone', con=engine, if_exists='replace', index=True)

2019-08-15 20:49:39,077 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'sql_mode'
2019-08-15 20:49:39,079 INFO sqlalchemy.engine.base.Engine {}
2019-08-15 20:49:39,192 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'lower_case_table_names'
2019-08-15 20:49:39,195 INFO sqlalchemy.engine.base.Engine {}
2019-08-15 20:49:39,212 INFO sqlalchemy.engine.base.Engine SELECT DATABASE()
2019-08-15 20:49:39,216 INFO sqlalchemy.engine.base.Engine {}
2019-08-15 20:49:39,225 INFO sqlalchemy.engine.base.Engine show collation where `Charset` = 'utf8mb4' and `Collation` = 'utf8mb4_bin'
2019-08-15 20:49:39,227 INFO sqlalchemy.engine.base.Engine {}
2019-08-15 20:49:39,253 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
2019-08-15 20:49:39,255 INFO sqlalchemy.engine.base.Engine {}
2019-08-15 20:49:39,261 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
2019-08-15 20:49:39,263 INFO sqlalchemy.engine.base.Engine {}
2019-08-15 20:49:39,268 INFO sqlalchemy.engine.base.Engine SELECT CAST('test collated returns' AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_bin AS anon_1
2019-08-15 20:49:39,270 INFO sqlalchemy.engine.base.Engine {}
2019-08-15 20:49:39,288 INFO sqlalchemy.engine.base.Engine DESCRIBE `df_ministop_twoplusone`
2019-08-15 20:49:39,294 INFO sqlalchemy.engine.base.Engine {}
2019-08-15 20:49:39,322 INFO sqlalchemy.engine.base.Engine ROLLBACK
2019-08-15 20:49:39,330 INFO sqlalchemy.engine.base.Engine
CREATE TABLE df_ministop_twoplusone (
	`index` BIGINT,
	`품명` TEXT,
	`가격` TEXT,
	`행사명` TEXT
)


2019-08-15 20:49:39,332 INFO sqlalchemy.engine.base.Engine {}

C:\Users\hieun\AppData\Local\Continuum\anaconda3\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect string value: '\\xB4\\xEB\\xC7\\xD1\\xB9\\xCE...' for column 'VARIABLE_VALUE' at row 1")
  result = self._query(query)

2019-08-15 20:49:39,727 INFO sqlalchemy.engine.base.Engine COMMIT
2019-08-15 20:49:39,731 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_df_ministop_twoplusone_index ON df_ministop_twoplusone (`index`)
2019-08-15 20:49:39,733 INFO sqlalchemy.engine.base.Engine {}
2019-08-15 20:49:40,335 INFO sqlalchemy.engine.base.Engine COMMIT
2019-08-15 20:49:40,348 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-08-15 20:49:40,353 INFO sqlalchemy.engine.base.Engine INSERT INTO df_ministop_twoplusone (`index`, `품명`, `가격`, `행사명`) VALUES (%(index)s, %(품명)s, %(가격)s, %(행사명)s)
2019-08-15 20:49:40,356 INFO sqlalchemy.engine.base.Engine ({'index': 0, '\ud488\uba85': '잼있는쿠키', '\uac00\uaca9': '900', '\ud589\uc0ac\uba85': '2+1'}, {'index': 1, '\ud488\uba85': '매일)99원액두유190ml', '\uac00\uaca9': '1000', '\ud589\uc0ac\uba85': '2+1'}, {'index': 2, '\ud488\uba85': '매일)헬로엔요200ml', '\uac00\uaca9': '800', '\ud589\uc0ac\uba85': '2+1'}, {'index': 3, '\ud488\uba85': '스키피피넛버터우유190ml', '\uac00\uaca9': '1200', '\ud589\uc0ac\uba85': '2+1'}, {'index': 4, '\ud488\uba85': '롯데진복분자180ml', '\uac00\uaca9': '1200', '\ud589\uc0ac\uba85': '2+1'}, {'index': 5, '\ud488\uba85': '델몬트180ml', '\uac00\uaca9': '1200', '\ud589\uc0ac\uba85': '2+1'}, {'index': 6, '\ud488\uba85': '신)제주삼다수500', '\uac00\uaca9': '950', '\ud589\uc0ac\uba85': '2+1'}, {'index': 7, '\ud488\uba85': '아로골드D드링크', '\uac00\uaca9': '1000', '\ud589\uc0ac\uba85': '2+1'}  ... displaying 10 of 180 total bound parameter sets ...  {'index': 178, '\ud488\uba85': '동서)티오피스무스240', '\uac00\uaca9': '1800', '\ud589\uc0ac\uba85': '2+1'}, {'index': 179, '\ud488\uba85': '티오피300ml', '\uac00\uaca9': '2200', '\ud589\uc0ac\uba85': '2+1'})
2019-08-15 20:49:40,379 INFO sqlalchemy.engine.base.Engine COMMIT